import { Feature } from "@/types/event";

const eventData: Feature[] = [
  {
    id: "1",
    slug: "tech-conference-2025",
    category: "Technology",
    categoryColor: "bg-blue-500",
    location: "San Francisco, CA",
    time: "March 30, 2025 - 2:00 PM",
    title: "Tech Conference 2025",
    description: "Join us for the annual tech conference featuring the latest innovations.",
    price: "$99",
    image: "/images.jpg",
  },
  {
    id: "2",
    slug: "harsh",
    category: "Technology",
    categoryColor: "bg-blue-500",
    location: "San Francisco, CA",
    time: "March 30, 2025 - 2:00 PM",
    title: "hrasrh",
    description: "kons.",
    price: "$99",
    image: "/images.jpg",
  },
  {
    id: "2",
    slug: "harsh",
    category: "Technology",
    categoryColor: "bg-blue-500",
    location: "San Francisco, CA",
    time: "March 30, 2025 - 2:00 PM",
    title: "hrasrh",
    description: "kons.",
    price: "$99",
    image: "/images.jpg",
  },
  {
    id: "2",
    slug: "harsh",
    category: "Technology",
    categoryColor: "bg-blue-500",
    location: "San Francisco, CA",
    time: "March 30, 2025 - 2:00 PM",
    title: "hrasrh",
    description: "kons.",
    price: "$99",
    image: "/images.jpg",
  },
];
export default eventData;